### ISSUE TITLE
Run memento-bg error 

### ISSUE THREAD

**Issue by 707367586** [apirrone/Memento#46]
os: monterey
device:macbook pro M1
python:3.10
------------------------------
error log:
Traceback (most recent call last):
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/bin/memento-bg", line 33, in <module>
    sys.exit(load_entry_point('memento', 'console_scripts', 'memento-bg')())
  File "/Users/zhoulingfeng/Desktop/code/Memento/memento/__init__.py", line 6, in bg
    backgound = Background()
  File "/Users/zhoulingfeng/Desktop/code/Memento/memento/background.py", line 77, in __init__
    self.workers[i].start()
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'sqlite3.Connection' object

**Comment by apirrone** [comment]
Hi, 

I have only tested the app on my system (Ubuntu 22.04) for now. This seems to be an issue with multiprocessing and sqlite, I will try to borrow a m1 macbook to try it out and see if I can reproduce your error.

Did you edit the code in `background.py` ? The line numbers don't seem to match with the current state of the main branch. If so, could you show what you edited ?

Thanks for trying out Memento :)

**Comment by 707367586** [comment]
tks for your reply. I use the origin code to run. this is the log  
memento-bg                        
pygame 2.5.0 (SDL 2.28.0, Python 3.10.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/bin/memento-bg", line 33, in <module>
    sys.exit(load_entry_point('memento', 'console_scripts', 'memento-bg')())
  File "/Users/zhoulingfeng/Desktop/code/Memento/memento/__init__.py", line 6, in bg
    backgound = Background()
  File "/Users/zhoulingfeng/Desktop/code/Memento/memento/background.py", line 75, in __init__
    self.workers[i].start()
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/zhoulingfeng/miniconda3/envs/memnto/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'sqlite3.Connection' object

**Comment by bradyab** [comment]
I'm also seeing this on a 2019 macbook running sonoma w/ intel silicon, python 3.11

**Comment by apirrone** [comment]
Hi @bradyab 

I suspect it is really just an issue with dependencies versions. I don't have an easy access to a Mac, so if you manage to make it work, please make a PR and I will merge it !

Thanks !

**Comment by aldrinjenson** [comment]
Hi, 
I'm facing the same issue on 2019 Intel Mac.
Any ideas on how to fix or debug this.?

**Comment by venturaEffect** [comment]
memento-bg not working.

**Comment by apirrone** [comment]
@aldrinjenson @venturaEffect Same answer than here :) https://github.com/apirrone/Memento/issues/51#issuecomment-2042045211

**Comment by venturaEffect** [comment]
Appreciate. Memento is really promising and I think it would even have demand if you launch it as a paid tool.
