### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by dzid26** [apirrone/Memento#51]
Is there even a chance for it to work on Windows?

Currently, `tesserocr` wheels doesn't compile on Windows and installed [binary](https://tesseract-ocr.github.io/tessdoc/Downloads.html) is not found.

Also, `OPENAI_API_KEY` cannot be found no matter what I do. I guess I need to try to restart the system as a last resort.  Yes, restarting actually helped somehow. 

```
> memento-bg
pygame 2.5.0 (SDL 2.28.0, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\dzidm\miniconda3\Scripts\memento-bg-script.py", line 33, in <module>
    sys.exit(load_entry_point('memento', 'console_scripts', 'memento-bg')())
  File "c:\users\dzidm\downloads\memento\memento\__init__.py", line 6, in bg
    backgound = Background()
  File "c:\users\dzidm\downloads\memento\memento\background.py", line 75, in __init__
    self.workers[i].start()
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'sqlite3.Connection' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\dzidm\miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

For now I am give up on this...

**Comment by apirrone** [comment]
Hi, 

This looks a lot like #46 but it was on MacOS.

I will investigate when I have time, It is easier for me to test things on Windows than MacOS, maybe I will find a solution for both :)

Thanks !

**Comment by hvsesha** [comment]
Hi 

Which version of Python are you using

**Comment by dzid26** [comment]
Python 3.10.12

**Comment by RobDiek** [comment]
any update regarding windows support? have the same problem with missing python lib when using the exe files.
I also tried using WSL2 for it however "display" doesnt get detected when I Try with an x server it says xrandr not deteted.
would L O V E to see this tool on windows, rewind for windows seems to take like months to complete and isnt osource

**Comment by apirrone** [comment]
Hi, I will try to put some work on it in the following days. I don't have a lot of free time these days but it should get better soon :)

**Comment by apirrone** [comment]
Indeed, the main issue seems to be that `tesserocr` wheel does not work on windows anymore from pip. I stumbled upon this thread https://github.com/sirfz/tesserocr/issues/287 . It seems to be possible to install it from `conda-forge` . I will try this.

As a last resort, it may be necessary to build tesserocr manually (https://github.com/sirfz/tesserocr/blob/master/Windows.build.md) which seems to be painful.

I'll keep you updated

**Comment by apirrone** [comment]
https://pypi.org/project/tesserocr/

The instructions under the `Windows/pip` section seems to have worked on my system 
![tesserocr_working](https://github.com/apirrone/Memento/assets/6552564/e5574e7a-7f21-420a-908c-b66afc3f06bd)

Now I have issues with `chroma`. Will continue to investigate later

**Comment by RobDiek** [comment]
just curious about any update? :)

**Comment by deepansharya1111** [comment]
> just curious about any update? :)

same here :)

**Comment by apirrone** [comment]
Hi all, sorry I don't have much free time to work on Memento these days ... I will update you here when I can give it some time !

**Comment by venturaEffect** [comment]
Any news of making it work on Windows 11? Appreciate

**Comment by venturaEffect** [comment]
Also not working in WSL. THis project seems to get abandoned. Sad, it looked promising.

**Comment by apirrone** [comment]
Hi @venturaEffect, I would not say the project is abandoned, I just don't have a lot of free time to work on side projects these days :) I have a few ideas to improve it, and I definitely should spend some time making it work on windows and macos. 

I will try to spend a few days on it soon, thank you for your interest anyway !
